// Generated by Supabase (generate_typescript_types) for project ilhcvnpzmhugzbxiqmdd.
// Do not edit by hand — regenerate after schema migrations.
// Standalone type definitions; not yet wired into the Supabase client.

export type Json =
  | string
  | number
  | boolean
  | null
  | { [key: string]: Json | undefined }
  | Json[]

export type Database = {
  // Allows to automatically instantiate createClient with right options
  // instead of createClient<Database, { PostgrestVersion: 'XX' }>(URL, KEY)
  __InternalSupabase: {
    PostgrestVersion: "14.5"
  }
  public: {
    Tables: {
      blocks: {
        Row: {
          blocked_id: string
          blocker_id: string
          created_at: string
        }
        Insert: {
          blocked_id: string
          blocker_id: string
          created_at?: string
        }
        Update: {
          blocked_id?: string
          blocker_id?: string
          created_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "blocks_blocked_id_fkey"
            columns: ["blocked_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "blocks_blocker_id_fkey"
            columns: ["blocker_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      follows: {
        Row: {
          created_at: string
          follower_id: string
          following_id: string
        }
        Insert: {
          created_at?: string
          follower_id: string
          following_id: string
        }
        Update: {
          created_at?: string
          follower_id?: string
          following_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "follows_follower_id_fkey"
            columns: ["follower_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "follows_following_id_fkey"
            columns: ["following_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      player_stats: {
        Row: {
          created_at: string
          id: string
          is_plausible: boolean | null
          metric_id: string
          notes: string | null
          profile_id: string
          updated_at: string
          value: number
          verification_method: string
          verified: boolean
        }
        Insert: {
          created_at?: string
          id?: string
          is_plausible?: boolean | null
          metric_id: string
          notes?: string | null
          profile_id: string
          updated_at?: string
          value: number
          verification_method?: string
          verified?: boolean
        }
        Update: {
          created_at?: string
          id?: string
          is_plausible?: boolean | null
          metric_id?: string
          notes?: string | null
          profile_id?: string
          updated_at?: string
          value?: number
          verification_method?: string
          verified?: boolean
        }
        Relationships: [
          {
            foreignKeyName: "player_stats_metric_id_fkey"
            columns: ["metric_id"]
            isOneToOne: false
            referencedRelation: "sport_metrics"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "player_stats_profile_id_fkey"
            columns: ["profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      profiles: {
        Row: {
          age_band: string | null
          avatar_url: string | null
          birth_year: number | null
          comments_enabled: boolean
          created_at: string
          cross_school_dms_enabled: boolean
          display_name: string | null
          edition_streak: number
          email: string | null
          eula_accepted_at: string | null
          following_sports: string[]
          grad_year: number | null
          handle: string | null
          id: string
          is_minor: boolean
          onboarded: boolean
          primary_sport: string | null
          school: string | null
          school_id: string | null
          streak_freezes_remaining: number
          theme_preference: string
          updated_at: string
        }
        Insert: {
          age_band?: string | null
          avatar_url?: string | null
          birth_year?: number | null
          comments_enabled?: boolean
          created_at?: string
          cross_school_dms_enabled?: boolean
          display_name?: string | null
          edition_streak?: number
          email?: string | null
          eula_accepted_at?: string | null
          following_sports?: string[]
          grad_year?: number | null
          handle?: string | null
          id: string
          is_minor?: boolean
          onboarded?: boolean
          primary_sport?: string | null
          school?: string | null
          school_id?: string | null
          streak_freezes_remaining?: number
          theme_preference?: string
          updated_at?: string
        }
        Update: {
          age_band?: string | null
          avatar_url?: string | null
          birth_year?: number | null
          comments_enabled?: boolean
          created_at?: string
          cross_school_dms_enabled?: boolean
          display_name?: string | null
          edition_streak?: number
          email?: string | null
          eula_accepted_at?: string | null
          following_sports?: string[]
          grad_year?: number | null
          handle?: string | null
          id?: string
          is_minor?: boolean
          onboarded?: boolean
          primary_sport?: string | null
          school?: string | null
          school_id?: string | null
          streak_freezes_remaining?: number
          theme_preference?: string
          updated_at?: string
        }
        Relationships: [
          {
            foreignKeyName: "profiles_school_id_fkey"
            columns: ["school_id"]
            isOneToOne: false
            referencedRelation: "schools"
            referencedColumns: ["id"]
          },
        ]
      }
      reports: {
        Row: {
          created_at: string
          id: string
          reason: string | null
          reporter_id: string
          target_profile_id: string
        }
        Insert: {
          created_at?: string
          id?: string
          reason?: string | null
          reporter_id: string
          target_profile_id: string
        }
        Update: {
          created_at?: string
          id?: string
          reason?: string | null
          reporter_id?: string
          target_profile_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "reports_reporter_id_fkey"
            columns: ["reporter_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "reports_target_profile_id_fkey"
            columns: ["target_profile_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
        ]
      }
      schools: {
        Row: {
          city: string | null
          created_at: string
          id: string
          latitude: number | null
          longitude: number | null
          name: string
          state: string | null
        }
        Insert: {
          city?: string | null
          created_at?: string
          id?: string
          latitude?: number | null
          longitude?: number | null
          name: string
          state?: string | null
        }
        Update: {
          city?: string | null
          created_at?: string
          id?: string
          latitude?: number | null
          longitude?: number | null
          name?: string
          state?: string | null
        }
        Relationships: []
      }
      sport_metrics: {
        Row: {
          created_at: string
          direction: string
          id: string
          key: string
          label: string
          max_13_15: number | null
          max_16_18: number | null
          max_19_plus: number | null
          min_13_15: number | null
          min_16_18: number | null
          min_19_plus: number | null
          sort_order: number
          sport: string
          unit: string | null
        }
        Insert: {
          created_at?: string
          direction: string
          id?: string
          key: string
          label: string
          max_13_15?: number | null
          max_16_18?: number | null
          max_19_plus?: number | null
          min_13_15?: number | null
          min_16_18?: number | null
          min_19_plus?: number | null
          sort_order?: number
          sport: string
          unit?: string | null
        }
        Update: {
          created_at?: string
          direction?: string
          id?: string
          key?: string
          label?: string
          max_13_15?: number | null
          max_16_18?: number | null
          max_19_plus?: number | null
          min_13_15?: number | null
          min_16_18?: number | null
          min_19_plus?: number | null
          sort_order?: number
          sport?: string
          unit?: string | null
        }
        Relationships: []
      }
      stat_cosigns: {
        Row: {
          cosigner_id: string
          created_at: string
          stat_id: string
        }
        Insert: {
          cosigner_id: string
          created_at?: string
          stat_id: string
        }
        Update: {
          cosigner_id?: string
          created_at?: string
          stat_id?: string
        }
        Relationships: [
          {
            foreignKeyName: "stat_cosigns_cosigner_id_fkey"
            columns: ["cosigner_id"]
            isOneToOne: false
            referencedRelation: "profiles"
            referencedColumns: ["id"]
          },
          {
            foreignKeyName: "stat_cosigns_stat_id_fkey"
            columns: ["stat_id"]
            isOneToOne: false
            referencedRelation: "player_stats"
            referencedColumns: ["id"]
          },
        ]
      }
      verification_requests: {
        Row: {
          created_at: string
          id: string
          method: string
          requester_id: string
          stat_id: string
          status: string
        }
        Insert: {
          created_at?: string
          id?: string
          method: string
          requester_id: string
          stat_id: string
          status?: string
        }
        Update: {
          created_at?: string
          id?: string
          method?: string
          requester_id?: string
          stat_id?: string
          status?: string
        }
        Relationships: [
          {
            foreignKeyName: "verification_requests_stat_id_fkey"
            columns: ["stat_id"]
            isOneToOne: false
            referencedRelation: "player_stats"
            referencedColumns: ["id"]
          },
        ]
      }
    }
    Views: {
      [_ in never]: never
    }
    Functions: {
      cosign_stat: { Args: { p_stat_id: string }; Returns: undefined }
      leaderboard: {
        Args: {
          p_limit?: number
          p_metric_key: string
          p_only_verified?: boolean
          p_scope: string
          p_sport: string
        }
        Returns: {
          handle: string
          profile_id: string
          rank: number
          ranked: boolean
          school_name: string
          value: number
          verification_method: string
          verified: boolean
        }[]
      }
      my_percentile: {
        Args: { p_metric_key: string; p_scope: string; p_sport: string }
        Returns: number
      }
      nearby_schools: {
        Args: { p_lat: number; p_limit?: number; p_lng: number }
        Returns: {
          city: string
          distance_km: number
          id: string
          name: string
          state: string
        }[]
      }
    }
    Enums: {
      [_ in never]: never
    }
    CompositeTypes: {
      [_ in never]: never
    }
  }
}

type DatabaseWithoutInternals = Omit<Database, "__InternalSupabase">

type DefaultSchema = DatabaseWithoutInternals[Extract<keyof Database, "public">]

export type Tables<
  DefaultSchemaTableNameOrOptions extends
    | keyof (DefaultSchema["Tables"] & DefaultSchema["Views"])
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
        DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? (DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"] &
      DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Views"])[TableName] extends {
      Row: infer R
    }
    ? R
    : never
  : DefaultSchemaTableNameOrOptions extends keyof (DefaultSchema["Tables"] &
        DefaultSchema["Views"])
    ? (DefaultSchema["Tables"] &
        DefaultSchema["Views"])[DefaultSchemaTableNameOrOptions] extends {
        Row: infer R
      }
      ? R
      : never
    : never

export type TablesInsert<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Insert: infer I
    }
    ? I
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Insert: infer I
      }
      ? I
      : never
    : never

export type TablesUpdate<
  DefaultSchemaTableNameOrOptions extends
    | keyof DefaultSchema["Tables"]
    | { schema: keyof DatabaseWithoutInternals },
  TableName extends DefaultSchemaTableNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"]
    : never = never,
> = DefaultSchemaTableNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaTableNameOrOptions["schema"]]["Tables"][TableName] extends {
      Update: infer U
    }
    ? U
    : never
  : DefaultSchemaTableNameOrOptions extends keyof DefaultSchema["Tables"]
    ? DefaultSchema["Tables"][DefaultSchemaTableNameOrOptions] extends {
        Update: infer U
      }
      ? U
      : never
    : never

export type Enums<
  DefaultSchemaEnumNameOrOptions extends
    | keyof DefaultSchema["Enums"]
    | { schema: keyof DatabaseWithoutInternals },
  EnumName extends DefaultSchemaEnumNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"]
    : never = never,
> = DefaultSchemaEnumNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[DefaultSchemaEnumNameOrOptions["schema"]]["Enums"][EnumName]
  : DefaultSchemaEnumNameOrOptions extends keyof DefaultSchema["Enums"]
    ? DefaultSchema["Enums"][DefaultSchemaEnumNameOrOptions]
    : never

export type CompositeTypes<
  PublicCompositeTypeNameOrOptions extends
    | keyof DefaultSchema["CompositeTypes"]
    | { schema: keyof DatabaseWithoutInternals },
  CompositeTypeName extends PublicCompositeTypeNameOrOptions extends {
    schema: keyof DatabaseWithoutInternals
  }
    ? keyof DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"]
    : never = never,
> = PublicCompositeTypeNameOrOptions extends {
  schema: keyof DatabaseWithoutInternals
}
  ? DatabaseWithoutInternals[PublicCompositeTypeNameOrOptions["schema"]]["CompositeTypes"][CompositeTypeName]
  : PublicCompositeTypeNameOrOptions extends keyof DefaultSchema["CompositeTypes"]
    ? DefaultSchema["CompositeTypes"][PublicCompositeTypeNameOrOptions]
    : never

export const Constants = {
  public: {
    Enums: {},
  },
} as const
